server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://47.96.114.231:3306/meite?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: zlp@zwj521
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: mt-weixin
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
swagger:
  base-package: com.zlp.api.weixin.impl.service
  title: SpringCloud2.x构建微服务电商项目-微信服务接口
  description: 该项目“基于SpringCloud2.x构建微服务电商项目”由每特教育|蚂蚁课堂版权所有，未经过允许的情况下，私自分享视频和源码属于违法行为。
  version: 1.1
  terms-of-service-url: www.mayikt.com
  contact:
    name: 97后互联网架构师-余胜军
    email: 644064779@qq.com
    url: www.mayikt.com
  enabled: true
wx:
  mp:
    configs:
      - appId: wx408daee2fb0a9feb
        secret: e7343f1734e311cb3130b435a38de9d1
        token: mayikt
wechat:
  defalutMsg: 亲您的问题，我们已经知晓，稍后为您做出答复！！！