server:
  port: 80
spring:
  application:
    name: mt-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      locator:
        enabled: true
      routes:
        - id: mt-weixin
          uri: lb://mt-weixin
          predicates:
            - Path=/mt-weixin/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1
        - id: mt-member
          uri: lb://mt-member
          predicates:
            - Path=/mt-member/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1
      x-forwarded:
        enabled: false